import { Location } from './locations.types';

export const CHILE_LOCATIONS: Location[] = [
  {
    id: 'antofagasta',
    name: 'Antofagasta',
    regionId: 'antofagasta',
    regionName: 'Antofagasta',
    latitude: -23.6509,
    longitude: -70.3975,
  },
  {
    id: 'arica',
    name: 'Arica',
    regionId: 'arica-y-parinacota',
    regionName: 'Arica y Parinacota',
    latitude: -18.4783,
    longitude: -70.3126,
  },
  {
    id: 'chillan',
    name: 'Chillan',
    regionId: 'nuble',
    regionName: 'Nuble',
    latitude: -36.6066,
    longitude: -72.1034,
  },
  {
    id: 'concepcion',
    name: 'Concepcion',
    regionId: 'biobio',
    regionName: 'Biobio',
    latitude: -36.8201,
    longitude: -73.0444,
  },
  {
    id: 'coquimbo',
    name: 'Coquimbo',
    regionId: 'coquimbo',
    regionName: 'Coquimbo',
    latitude: -29.9533,
    longitude: -71.3395,
  },
  {
    id: 'copiapo',
    name: 'Copiapo',
    regionId: 'atacama',
    regionName: 'Atacama',
    latitude: -27.3668,
    longitude: -70.3319,
  },
  {
    id: 'iquique',
    name: 'Iquique',
    regionId: 'tarapaca',
    regionName: 'Tarapaca',
    latitude: -20.2307,
    longitude: -70.1357,
  },
  {
    id: 'la-serena',
    name: 'La Serena',
    regionId: 'coquimbo',
    regionName: 'Coquimbo',
    latitude: -29.9027,
    longitude: -71.2519,
  },
  {
    id: 'osorno',
    name: 'Osorno',
    regionId: 'los-lagos',
    regionName: 'Los Lagos',
    latitude: -40.5745,
    longitude: -73.1335,
  },
  {
    id: 'puerto-montt',
    name: 'Puerto Montt',
    regionId: 'los-lagos',
    regionName: 'Los Lagos',
    latitude: -41.4693,
    longitude: -72.9424,
  },
  {
    id: 'punta-arenas',
    name: 'Punta Arenas',
    regionId: 'magallanes-y-la-antartica-chilena',
    regionName: 'Magallanes y la Antartica Chilena',
    latitude: -53.1638,
    longitude: -70.9171,
  },
  {
    id: 'rancagua',
    name: 'Rancagua',
    regionId: 'libertador-general-bernardo-ohiggins',
    regionName: "Libertador General Bernardo O'Higgins",
    latitude: -34.1708,
    longitude: -70.7444,
  },
  {
    id: 'santiago',
    name: 'Santiago',
    regionId: 'metropolitana-de-santiago',
    regionName: 'Metropolitana de Santiago',
    latitude: -33.4489,
    longitude: -70.6693,
  },
  {
    id: 'talca',
    name: 'Talca',
    regionId: 'maule',
    regionName: 'Maule',
    latitude: -35.4264,
    longitude: -71.6554,
  },
  {
    id: 'temuco',
    name: 'Temuco',
    regionId: 'la-araucania',
    regionName: 'La Araucania',
    latitude: -38.7359,
    longitude: -72.5904,
  },
  {
    id: 'valdivia',
    name: 'Valdivia',
    regionId: 'los-rios',
    regionName: 'Los Rios',
    latitude: -39.8196,
    longitude: -73.2452,
  },
  {
    id: 'valparaiso',
    name: 'Valparaiso',
    regionId: 'valparaiso',
    regionName: 'Valparaiso',
    latitude: -33.0472,
    longitude: -71.6127,
  },
  {
    id: 'vina-del-mar',
    name: 'Vina del Mar',
    regionId: 'valparaiso',
    regionName: 'Valparaiso',
    latitude: -33.0245,
    longitude: -71.5518,
  },
];
